let ValidationError,DEBUG_MODE,CustomErrorHandler;_f2a‍.x([["default",()=>_f2a‍.o]]);_f2a‍.w("joi",[["ValidationError",["ValidationError"],function(v){ValidationError=v}]]);_f2a‍.w("../config",[["DEBUG_MODE",["DEBUG_MODE"],function(v){DEBUG_MODE=v}]]);_f2a‍.w("../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);



const errorHandler = (err, req, res, next) => {
  let statuscode = 500;
  let data = {
    message: "Internal server error",
    ...(DEBUG_MODE === "true" && { originalError: err.message }),
  };

  // if error is a validation error
  if (err instanceof ValidationError) {
    statuscode = 422;
    data = {
      message: err.message,
    };
  }

  // if error is a custom error
  if (err instanceof CustomErrorHandler) {
    statuscode = err.status;
    data = {
      message: err.message,
    };
  }

  return res.status(statuscode).json(data);
};

_f2a‍.d(errorHandler);
